### ISSUE TITLE
Object graph save (within transaction)

### ISSUE THREAD

**Issue by Allann** [object/Simple.OData.Client#101]
Hi,
This is not an issue as such, more a question of how.  My issue is that I have a parent entity that contains children.  I can't save the parent without having the children.  I found your modifying data wiki page, but this does it in 2 separate calls (as far as I understand the calls).
I have a built object hierarchy that I send, but when it gets to the server, only the parent exists in the body.  Therefore requiring a separate call with all the child records.  But I need to server to commit all or none within a single transaction. 
How can I achieve this?  I am thinking the only way is to create a function and pass the object graph, but that seems like a work-around.  Many people must do this already as it's not an uncommon requirement.
Thanks in advance.

**Comment by object** [comment]
Hi Allan,

Since this is a more of a discussion topic than the issue, I suggest you post it in the Google group that I recently created for such purposes. Then these topics will be available for everyone to discuss and search.

Here's the group: https://groups.google.com/forum/#!forum/simpleodataclient
