### ISSUE TITLE
NullReferenceException when creating a Session

### ISSUE THREAD

**Issue by Allann** [object/Simple.OData.Client#108]
Hi

After your recent changes, I now get a NullReferenceException when creating a client with no Uri set in the passed in settings.  This used to work and my code relies heavily on this feature.

var mySettings = new ODataClientSettings();
var myClient = new ODataClient(mySettings);
var myService = new EnvironmentService(myClient);

internally this is called:
private Session(ODataClientSettings settings)

and then fails in
    this.MetadataCache = MetadataCache.Instances.GetOrAdd(this.Settings.BaseUri.AbsoluteUri, new MetadataCache());

because BaseUri is null.

Suggest making the Uri in settings mandatory if this is expected behavior and I'll find another way of creating the client to pass to the service.

**Comment by object** [comment]
Oops, that's bad regression. Will have a look asap.

**Comment by object** [comment]
I've uploaded 4.5.1 that throws InvalidOperationException if it encounters empty URI in ODataClientSettings. Unfortunately I can not make URI mandatory at construction unless I do a major version upgrade because some existing code will fail to compile. But the fact that earlier it accepted empty values on ODataClient creation was wrong, so you are not supposed to create a client from settings with empty URI. You will have to change your code, sorry for the changed behaviour, but old behaviour was incorrect, it may create erroneous situation.

**Comment by Allann** [comment]
Thank you.  I went through my code and changed it all yesterday (not a big change really).
