### ISSUE TITLE
Target SL5

### ISSUE THREAD

**Issue by tomcrusader** [object/Simple.OData.Client#114]
I created an PCL project for connecting to an OData 4 source from Silverlight 5.

While I see there's an sl5 folder in the Simple.OData.Client.4.6.0 package, trying to install it in my PCL targeting .Net 4.5+SL5 (TargetFrameworkProfile 24) I get an error:

> Install-Package : Could not install package 'Simple.OData.Client 4.6.0'. You are trying to install this package into a project that targets 'portable-net45+sl50', but the package does not contain any assembly references or co
ntent files that are compatible with that framework. For more information, contact the package author.

Well - you're the author :)

**Comment by object** [comment]
I believe the problem is that you are using the Simple.OData.Client from a PCL project, not from a SL5 application. That won't work because OData client PCL is in fact 3 libraries: a PCL (profile 259, .NET 4.5, Windows 8, WinPhone 8.1, WinPhone 8 but not Silverlight), a .NET 4.0 library and a Silverlight 5 library. So when you are trying to reference OData client lib from your PCL, you get an error saying that there is no compatible assebly, and this is correct. This scenario is not supported.

And the reason it's not supported is that originally I built a single PCL that targeted all possible platforms, but such one-size-fits-all PCL didn't work well with Xamarin apps, neither was it stable. I remember having various issues with HttpClient PCL (that is referenced from OData client). Eventually I gave up and switched to this composite scenario sacrificing possibility to reference OData client from a PCL that targets SL5.

What are your options? The easiest is to do the same: build your PCL as a set of 2 libraries: one targeting all but SL5 (259 profile works well but you can try others) and another one just targeting SL5. Then you can both reference Simple.OData.Client and use your PCL for multiple platforms.

Of course you can fork Simple.OData.Client and change its PCL profile but I suspect you're going to regret. For the same reasons that I did.

**Comment by tomcrusader** [comment]
For the current implementation we don't need to involve PCL, and can go straight at the SL project :)
