### ISSUE TITLE
System.Threading.Tasks

### ISSUE THREAD

**Issue by micah8719** [object/Simple.OData.Client#143]
It appears that this library is not referencing the System.Threading.Tasks in the Microsoft.Bcl package, so warnings like:

```
Severity	Code	Description	Project	File	Line
Warning		The dependency 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of the assembly 'Simple.OData.Client.V4.Adapter, Version=4.10.0.0, Culture=neutral, PublicKeyToken=null' was not found. Please review the project's references.	Vidant.Mobile.iOS		
```

and

```
Severity	Code	Description	Project	File	Line
Warning		Could not compute a complete dependency map for the project. This will result in slower build times because Xamarin.iOS can't properly detect what needs to be rebuilt (and what does not need to be rebuilt). Please review previous warnings for more details.	Vidant.Mobile.iOS	
```

**Comment by object** [comment]
Thank you for the notice. I will check this out. But I believe the application should work, it's just a warning?

**Comment by micah8719** [comment]
Yes, but there are several other warnings. It causes the build session to take a little longer than normal because it can't correctly compute a dependency map. The functionality is great, though, by the way. I've really enjoyed using this library. Thanks for your contribution.

**Comment by object** [comment]
OK, I will investigate this further.

**Comment by object** [comment]
Hi again,
I am a little uncertain if this is an issue with the library. The library projects include Microsoft.Bcl NuGet package so they have all they need. But isn't it the client app that lacks the references? Do you include Microsoft.Bcl (in some cases Microsoft.Bcl.Async) in your app? Since Simple.OData.Client libraries are PCLs, I can't reference directly System.Threading.Task.
