### ISSUE TITLE
Clarification on the 'FilterIsKey' property needed

### ISSUE THREAD

**Issue by thomasbeste** [object/Simple.OData.Client#188]
Hi,

I need to clarify how the FilterIsKey works. I have an OData V3 query. the query has two values supplied which is the combined key for a single result. When the query is generated simple.odata.client knows this, since it formats the query for a single action request, however, the FilterIsKey = false, and i would expect it to be true.

I need this, to know if i should fire the GetEntry or GetEntries function :-) 

Any help would be greatly appreciated

**Comment by object** [comment]
Hi,

FilterIsKey is evaluated internally by the library in order to format query URI. It is not supposed to be used by the client. Basically the client just specifies the filter and the library figures out if it should format the request as a key lookup or a standard query.

**Comment by thomasbeste** [comment]
Thank you for the reply. Do i have any way of evaluating if i should run the FindEntry or FindEntries, which i have not yet found? :)

**Comment by object** [comment]
The evaluation is simple: if fields specified in a filter represent the entity key, the query will be evaluated as a key lookup (corresponding to GetEntry), otherwise if will be formatted using query string (corresponding to FindEntry/FindEntries). And usually you don't need to think about it, the library will format the request in a right way.

If you are certain this is a lookup query, you can use GetEntry, otherwise use FindEntry if you only want to select a single result, and FindEntries if you want all results. In case this is not a key lookup it's not possible to figure out up front whether you will get one or many results.
