### ISSUE TITLE
Can I use my own Repository/HTTPClient implementation?

### ISSUE THREAD

**Issue by xplatsolutions** [object/Simple.OData.Client#214]
This library is the closest to what I would like to have. Writing LINQ queries and calling my Web API OData REST service.

I have a question, as far as Injnderstand this is not abstracted to just use the LINQ provider and retrieve the OData query so that I can just attach it in my own repository implementations.

Example would be, I use my own HTTPClient setup and configuration and making the calls to my service but I would like to support Expression parameters and retrieve the OData translation of the Expression.

Is it possible to just use the LINQ provider or a workaround? Maybe another library close to what I need?

Keep up with the great job.

**Comment by object** [comment]
Thank you for your interest in the library. I think we should be careful with using term "LINQ provider" when it comes to Simple.OData.Client because it doesn't implement classical LINQ provider similar to SQL database LINQ providers or LINQ to objects. I tried to describe reasons for my choice in this article: http://www.codeproject.com/Articles/686240/reasons-to-consume-OData-feeds-using-Simple-ODa

Having said that, the library does support parsing LINQ expressions and it's easy to build OData queries by combining ODataExpression objects, for example:

`            Expression<Predicate<TestEntity>> condition1 = x => x.ProductName == "Chai";
            Expression<Func<TestEntity, bool>> condition2 = x => x.ProductID == 1;
            Expression<Predicate<TestEntity>> condition3 = x => x.ProductName == "Kaffe";
            Expression<Func<TestEntity, bool>> condition4 = x => x.ProductID == 2;
            var filter1 = new ODataExpression(condition1) || new ODataExpression(condition2);
            var filter2 = new ODataExpression(condition3) || new ODataExpression(condition4);
            var filter = filter1 && filter2;
            Assert.Equal("(ProductName eq 'Chai' or ProductID eq 1) and (ProductName eq 'Kaffe' or ProductID eq 2)", filter.AsString(_session));
`

Please a look at some tests that should be more or less self-explanatory:
https://github.com/object/Simple.OData.Client/blob/master/Simple.OData.Client.Tests.Core/TypedExpressionsTests.cs

**Comment by xplatsolutions** [comment]
Thank you. Looks like that this will do the job as needed to just append the resulting string in the endpoint URI.

Great job!
