### ISSUE TITLE
OData v4 Create not returing result - 8.3.3 Header OData-EntityId

### ISSUE THREAD

**Issue by cjrosa** [object/Simple.OData.Client#222]
Upon requesting the creation of a entity (via the CRM 2016 Web Api - https://msdn.microsoft.com/en-us/library/gg328090.aspx) the resulting entity is not returned from `InsertEntryAsync()`.

In reviewing the ODataClient.Internals code it would appear it's expecting a status != NoContent but that's exactly what the response would be in practice and via the OData spec section 8.3.3.

```
HTTP/1.1 204 No Content
OData-Version: 4.0
OData-EntityId: [organization URI]/api/data/v8.0/accounts(7eb682f1-ca75-e511-80d4-00155d2a68d1)
```

I modified the lib's `ExecuteRequestWithResultAsync()` method (locally) as follows and it works:

`                    IEnumerable<string> values = null;

                    if (response.IsSuccessStatusCode && (request.Method == RestVerbs.Get || request.ResultRequired))
                    {
                        if (response.StatusCode != HttpStatusCode.NoContent)
                        {
                            var responseReader = _session.Adapter.GetResponseReader();

                            return createResult(await responseReader.GetResponseAsync(response));
                        }
                        // THIS IS THE ADDED PART (w/ a bit of logic refactoring around it too)
                        else if (response.Headers.TryGetValues("OData-EntityId", out values))
                        {
                            return (T)await FindEntryAsync(values.First());
                        }
                    }`

But I'm wondering if I'm missing something.

Thanks,
Chris

**Comment by object** [comment]
Do you set "Prefer" header to "ReturnRepresentation"? I believe this is what's needed to obtain results.

**Comment by object** [comment]
I suppose setting the right header fixed it.

**Comment by somefella123** [comment]
Looks like this is a valid issue (and still present) - the Prefer header is set correctly to return=representation, the Odata-Entity-Id field is populated by CRM's response (as is the Location header), but then nothing is done with this header response by the library because they form part of a 204 response and hence not processed any further.

For an http 204 following a POST, I think the library either needs to return the Location & OData-entity-Id header values, or it needs to perform a get of the entity created and return that entity.  (Personally my preference is to just give me back the Ids so I can choose whether to incur the penalty of an http get).

Just to illustrate, here's a snip from Fiddler:

```
Request:
Prefer: return=representation

Response:
OData-EntityId: http://(redacted)/api/data/v8.1/myentity(4b20c7b3-9b6e-e611-80e7-000d3a22a76f)
Location: http://(redacted)/api/data/v8.1/myentity(4b20c7b3-9b6e-e611-80e7-000d3a22a76f)

```
