### ISSUE TITLE
Converting Expression to filter string

### ISSUE THREAD

**Issue by matjanos** [object/Simple.OData.Client#430]
Hello, 
Is this possible to simply convert an expression (precisely `Expression<Func<Product, bool>>`), to a filter query like `(status eq 3 or status eq 7 or status eq 2) and (type eq 6 or type eq 3)`? 

I believe that the client does it under the hood, but I don't need the entire querying for metadata and so on.

Cheers, Kuba.

**Comment by object** [comment]
Sorry for the late response. Yes it is possible. Example:

You can use GetCommandTextAsync to obtain just the command text. You can also set a metadata document on ODataClientSettings to avoid calling into the OData server. But you must have metadata in order to evaluate the expression, because the evaluation may depend on metadata details (for example, the name of the field may be transformed according to the metadata).

Hope this helps.
