### ISSUE TITLE
Rationale of v5 nuget packaging?

### ISSUE THREAD

**Issue by phatcher** [object/Simple.OData.Client#472]
Why are there different nuget packages for net45 and netstandard2.0 given that its easy to multi-target projects towards both frameworks?

This would allow us to rationalize the testing projects for example.

**Comment by object** [comment]
Hi @phatcher,

As you may have noticed, I abandoned the work on the library for several months due to being overloaded with other stuff. Now that I finally got some time I decided first to push as quickly as possible support for .NET Standard 2.0 without changing much of existing structure. It is right what you suggest and it doesn't affect the actual library functionality, it's just packaging. If you have time to send me a PR (or just commit directly if we discuss the changes first), then just go ahead. Or I can do it shortly.

**Comment by phatcher** [comment]
@object On my version of the v5 branch I've converted all the projects to VS2017 format as that allows me to get things transitive nuget dependencies and automatic nuget packaging very simply.

It also makes it easier to produce test assemblies per framework e.g. a net45 and netcoreapp2.0 version of each test assembly that wires up to the appropriate nuget packages; this mitigates against missing  framework differences.

I'll merge your current v5 stuff on to mine and we can have a conversation as to whether you want the changes - I can also integrate a simple paket/Fake build script which means its easy to build/test everything from the command line, see https://github.com/phatcher/CsvReader for example.

**Comment by object** [comment]
This sounds good, and we should start using Paket.

**Comment by phatcher** [comment]
@object I've pushed my v5 branch, summary as follows...

1. All projects converted to VS2017 format with exception of the services + old test projects e.g. Android, Touch
2. Projects now target net45, net462, net472 and netstandard2.0 - this supports current frameworks whilst avoiding the compatibility shims for netstandard
3. Core takes a dependency on Microsoft.AspNet.WebApi.Client, this gets us the HttpRequestMessage etc for both net and netstandard and avoids the Microsoft.Net.Http references- will allow us to introduce Polly etc later on.
4. Simple.OData.Client.Net45 is obsoleted as Core, Dynamic, V3/V4 Adapter now multi-target
5. Some tests failing, but they are failing in the current v5 branch, typically around media support but there are a couple of Northwind v3 tests that fail
6. Test framework updated, tests now visible via the Resharper test runner as well as VS
7. Made V3/V4 Adapter take a dependency on Dynamic as well as Core so automatic package build will be easier

Let me know what you think - I'll incorporate a build script next

**Comment by object** [comment]
Oops, looks like I partly did what you did - just pushed similar changes (my fault because we kind of agreed that I you should do this part). But your changes cover more stuff, so I will fetch your v5 and merge with mine. Thanks!

**Comment by object** [comment]
Hi again.
I justed completed merge from your branch, resolved some conflicts and pushed the updated package 5.0.1. Thanks a lot for your work, it's highly appreciated. Below are the comments regarding how it looks now:

1. I kept most of the changes you did, all projects that can use 2017 format use it.
2. I removed Simple.OData.Client.Net45 since it's now obsolete.
3. I also removed iOS/Android test projects as well as Mono solution. They are very old, I used them mostly to try something on the phone. This can be achieved differently when needed.
4. I didn't yet include dependency on Microsoft.AspNet.WebApi because I want to keep the library minimalistic, for example without referencing Newtonsoft.Json that Microsoft.AspNet.WebApi references. Yes, I had to reference Microsoft.Net.Http for net452 build but that's more lightweight than bringing AspNet stuff. If you think there are other reasons to include that packages, let me know.
5. I increased mininal supported .NET FX version to 4.5.2 after investigating what's recommended. 4.5 is no longer supported, and I was recommended not to go below 4.5.2.
6. There may be reasons for explicitly targeting 4.6.X and 4.7.X but that's typically in case they contain some new API. At the moment I can't see what we gain from targeting these frameworks. Again, I want the library to be minimalistic and have specific reasons for targeting certain versions of frameworks. And if I overlook something, let me know.

Thanks again!

**Comment by phatcher** [comment]
Next steps if you agree...

1. Merge test assembly Any.Client/Core/Net45/NetStandard and multi-target, this should give us testability on non-Windows platforms
2. Can V3/V4 Client.Tests be deleted as I think IntegrationTests cover this off

**Comment by object** [comment]
3. If not targeting other 4.x assemblies becomes PITA during the build, then this might be a reason for including more frameworks in the package (but I would still investigate more). But I am skeptical about dragging more dependencies into such simple library (including JSON.NET) for the sake on build of 3rd party projects. Are there other ways to resolve this problem? Add Microsoft.AspNet.WebApi.Client directly to those projects?

**Comment by object** [comment]
Oh, I forgot to mention the role of 3 special test projects: Any.Client.Tests, V3.Client.Tests and V4.Client.Tests. Those are part of AcceptanceTests solution, they are not included in main solution because I don't reference library projects directly there. Instead I reference newest Simple.OData.Client NuGet packages. So this is a quick way to test that I didn't break something before pushing NuGet packages. I changed them so they don't reference library projects directly, I also removed them from the main solution.

**Comment by object** [comment]
And I guess V3/V4 client.Tests can probably be deleted. Before they were targeting different library versions. Now they are kind of the same.

**Comment by object** [comment]
And Any.Client.Tests then can be renamed to something like Package.Tests because it references NuGet package. Then it will be easy to understand its purpose.

**Comment by phatcher** [comment]
We could rename the central test assembly to Simple.OData.Clients.Tests though there's one issue with resource designer files that I've hit elsewhere which means we might need to keep two test assemblies

**Comment by object** [comment]
And while speaking about dependencies, why should V3 and V4 adapters reference Dynamic lib? They are not using dynamic syntax. Are there any situations when not having reference to Dynamic can become a problem? The Dynamic syntax library is always installed together with Core from a Nuget package, isn't this sufficient?

**Comment by phatcher** [comment]
I was thinking of automating the nuget dependencies; V3/V4 have a reference to Core, if they also have a reference to Dynamic then you have a complete set for any particular OData source

**Comment by object** [comment]
But the graph is somewhat different:
Core
   -- Dynamic
   -- V3
   -- V4
I.e. three packages (Dynamic, V3, V4) all have dependency on Core. So I believe there is no need for them to cross-reference each other. Let's say we need to restructure NuGet packages so people will not get Dynamic unless they want it. Then we can have the following split:
Core package (only includes Core)
Dynamic package (Dynamic + references Core lib)
V3 package (V3 + references Core lib)
V4 package (V4 + references Core lib)
If V3/V4 reference Dynamic, this won't be possible even though they don't use it. And I don't see what advantage can anyone get from V3/V4 referencing Dynamic.

**Comment by object** [comment]
@phatcher, I did some solution/project cleanup. Both v5 and master are updated.

**Comment by phatcher** [comment]
@object I did some minor changes e.g. fix the documentation output path and updated the build script to point at the new solution.

1. Does TestUtils still need to exist, the code is only used in UnitTests
2. Can/should Tests.Core and UnitTests be merged

**Comment by object** [comment]
1. One of the reasons for having TestUtils was that it had a wrapper for WCF Data Service that I used to spawn Northwind test OData service. We will still need it if we want to re-create mock data, and WCF Data Services are not supported by NetStandard, so it can be merge with the main test project but with conditional reference to WCF Data Services. 
2. Second reason is that now it has HttpMock helper class that is used in other test projects for V3 and V4 adapters. But they can link the mocker class from the main test project.
3. Test.Core and UnitTests should probably be merged.

**Comment by phatcher** [comment]
Do you want to do it, or should I do it on my branch and you can merge it back?

**Comment by object** [comment]
You can do it in your branch, I can merge later.
BTW, I am now using multitargeting in Test project, but I only see tests for 4.5.2 target in Resharper test list, nothing for .netcore2.

**Comment by phatcher** [comment]
Yeah, I noticed that and have raised a bug with Resharper - seems quite random as I have other solutions where it works fine.

**Comment by object** [comment]
I updated R# to the latest version and now it recognizes .NET Core tests.
