### ISSUE TITLE
Poor Performance

### ISSUE THREAD

**Issue by thomasklammer** [object/Simple.OData.Client#494]
Hi,

is it possible that every call regardless on which functionality takes up to 10 seconds?
I'm using it to transfer data to dynamics crm 365. The webapi is fast on postman but pretty slow with Simple.OData.Client. 

Follow this link for more information: [https://stackoverflow.com/questions/51043200/simple-odata-client-really-slow]([https://stackoverflow.com/questions/51043200/simple-odata-client-really-slow)

**Comment by object** [comment]
The performance you are experiencing is absolutely unacceptable. I know that this often happens with developers using the library with Dynamic CRM 365. I noticed that OData schema for Dynamic CRM is often very large and suspect this might have something to do with slowness around schema lookups.

In order to further investigate the issue I need the following:
1. A copy of the schema (got to <service url>/$metadata and download the XML file).
2. A code snippet of URL that it generates that produces the result that take so long time to fetch.
3. A JSON result that is returned by the server (you can obtain it from Postman or a similar tool).

**Comment by phatcher** [comment]
@object When you get this, can you forward it to me also, or put it in as a test

**Comment by object** [comment]
@phatcher thanks, will do!

**Comment by thomasklammer** [comment]
@object how can I send you the data?

**Comment by object** [comment]
You can send them to vagif.abilov at gmail.com.

**Comment by toryb** [comment]
I am also using the library to access Dynamics CRM 365. According to Fiddler, the $metadata body is 3.4 meg. Is there a way that we could provide the metadata via a stream or something?

**Comment by object** [comment]
@toryb Metadata document is large, I suspect this might be a source of performance problems even though there is a room for optimization here. AFAIK metadata can't be exposed as a stream, and this wouldn't make much sense since the purpose of metadata is to provide instant access to service resource description.

**Comment by object** [comment]
@thomasklammer I ran some benchmarks using your data and mocked service and results were retrieved pretty fast, within 20-25 ms. So it might be something else.
This is what I did:
1. Assigned MetadataDocument in ODataClientSettings to the schema file that you provided
2. Since I don't have access to your service, I mocked service response, i.e. assigned your JSON result to a response as if it was returned by the service.
3. Measured time it takes from sending a request to completing the call (using FindEntriesAsync or FindEntryAsync).

The average time was always within 25 ms.
Can it be that the service takes so long time to respond? Another thing you might try is assign the metadata file you sent me to MetadataDocument in ODataClientSettings. Please let me know if you find and differences.

**Comment by object** [comment]
These are my benchmark results where I increased number of rows in GetAll scenario from 2 to 10:

    Method |     Mean |     Error |    StdDev |
---------- |---------:|----------:|----------:|
    GetAll | 30.62 ms | 0.5653 ms | 0.5287 ms |
 GetSingle | 24.10 ms | 0.2581 ms | 0.2288 ms |

**Comment by object** [comment]
The benchmark project is available in v5 branch (Simple.OData.Client.Benchmarks). /cc @phatcher

**Comment by thomasklammer** [comment]
Ok it works a lot faster if i assign the metadata in ODataClientSettings. That should be the solution. 
I noticed that it loads a very long time if I request metadata on the server.

**Comment by object** [comment]
@thomasklammer Good that we have found a workaround. However, there is something fishy both with why it takes so long time to request metadata on the server (it's something for you to investigate, it has nothing to do with the library) and why the metadata is not cached. In principle once the metadata file is obtained it should be cached for any given service URL and reused for subsequent sessions. If you can inspect the network traffic (e.g. using Fiddler) and see that metadata is requested for each call, this is something for me to investigate further.

**Comment by mwchan** [comment]
Just wanted to chime in and see if it helps. I experienced performance issues in 5.0.0 beta 2 and had to do the following:

In ResponseReader.cs, it looks like the Annotations are always included. I created added a property in the settings to exclude it. The line that I am referring to is

`entryNode.Entry.SetAnnotations(CreateAnnotations(odataEntry));`

I also noticed that there is a behaviour change in v5 where I now cannot create a new instance of the ODataClient everytime I need it as it seems to be an expensive process in v5 since it keeps hitting the $metadata endpoint.

**Comment by zivillian** [comment]
#435 introduced a bug, which defeats the metadata cache is the ODataClientSettings are not reused. I'm working on a fix, which will solve the caching problem for metadata (zivillian@4345d57).

**Comment by object** [comment]
Thanks, @zivillian, appreciated!

**Comment by object** [comment]
Thanks to PR from @zivillian metadata cache should work fine again in 5.3. This should solve poor performance issue when creating multiple instances of ODataClient.

**Comment by object** [comment]
Version 5.3 is released. Metadata document should be reused again.
