### ISSUE TITLE
Docs - pledgie link (expired)

### ISSUE THREAD

**Issue by jafin** [object/Simple.OData.Client#518]
I updated the code snippets in the wiki to csharp/xml syntax.  Apologies in advanced if I accidentially broke a page, happy to fix.

I actually thought I could push the changes as  PR but couldn't see a way in github. 

Also just a heads up the pledgie link on https://github.com/object/Simple.OData.Client/wiki is broken (they are shutdown) did not want to remove it without consultation.

**Comment by object** [comment]
Thank you for the initiative. It's a long time since I touched documentation, it needs more love, so your contribution is highly appreciated. I removed myself pledgie link, and you should be able to open a PR for other changes. It's very easy using GitHub and described at their pages: https://help.github.com/articles/creating-a-pull-request/

So just go ahead and open a PR.

**Comment by object** [comment]
Wow. This really sucks. Then I guess I should add you as a collaborator. I have generated an invitation to you.

**Comment by jafin** [comment]
Thanks @object !
